services:
  pocketbase:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - pb_data:/pb/pb_data
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pb_data:
    name: pb_data
